<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Wheel Macro -->
    <xacro:macro name="wheel_macro" params="id r_wheel width_wheel collision_factor roller_radius roller_width">
    <link name="wheel_link_${id}">
            <visual>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1.0"/>
                </material>
            </visual>
        <!-- Roller 1 -->
        <visual>
            <origin xyz="${r_wheel} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>


        <!-- Roller 2 -->
        <visual>
            <origin xyz="${r_wheel * cos(0.628319)} ${r_wheel * sin(0.628319)} 0" rpy="0 0 0.628319"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>


        <!-- Roller 3 -->
        <visual>
            <origin xyz="${r_wheel * cos(1.25664)} ${r_wheel * sin(1.25664)} 0" rpy="0 0 1.25664"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>


        <!-- Roller 4 -->
        <visual>
            <origin xyz="${r_wheel * cos(1.88496)} ${r_wheel * sin(1.88496)} 0" rpy="0 0 1.88496"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>


        <!-- Roller 5 -->
        <visual>
            <origin xyz="${r_wheel * cos(2.51327)} ${r_wheel * sin(2.51327)} 0" rpy="0 0 2.51327"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
                <!-- Roller 6 -->
        <visual>
            <origin xyz="${r_wheel * cos(3.14159)} ${r_wheel * sin(3.14159)} 0" rpy="0 0 3.14159"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>

                <!-- Roller 7 -->
        <visual>
            <origin xyz="${r_wheel * cos(3.76991)} ${r_wheel * sin(3.76991)} 0" rpy="0 0 3.76991"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>

                <!-- Roller 8 -->
        <visual>
            <origin xyz="${r_wheel * cos(4.39823)} ${r_wheel * sin(4.39823)} 0" rpy="0 0 4.39823"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>

                <!-- Roller 9 -->
        <visual>
            <origin xyz="${r_wheel * cos(5.02655)} ${r_wheel * sin(5.02655)} 0" rpy="0 0 5.02655"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>

                <!-- Roller 10 -->
        <visual>
            <origin xyz="${r_wheel * cos(5.65487)} ${r_wheel * sin(5.65487)} 0" rpy="0 0 5.65487"/>
            <geometry>
                <cylinder radius="${roller_radius}" length="${roller_width}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel/collision_factor}"/>
                </geometry>
            </collision>

            <!--Inertia estimated for solid cylinder of radius 2.5" and height 1" with mass 1 lb-->
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.4545"/>
                <inertia
                    ixx="0.000482" ixy="0.0" ixz="0.0"
                    iyy="0.000482" iyz="0.0"
                    izz="0.000914"/>
            </inertial>
    </link>

    <gazebo reference="wheel_${id}">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder>
                    <radius>${r_wheel}</radius>
                    <length>${width_wheel/collision_factor}</length>
                </cylinder>
            </geometry>

            <surface>
                <friction>
                    <torsional>
                        <coefficient>1.0</coefficient>
                        <patch_radius>0.01</patch_radius>
                    </torsional>
                </friction>
            </surface>
        </collision>

        <material>Gazebo/White</material>
    </gazebo>
    </xacro:macro>
</robot>