<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>2025_autonomy_comms</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="ssnanjundiah@utexas.edu">ocuver43</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  
  // I borrowed these lines from the ghost_autonomy package.xml, we might need them
  <depend>behaviortree_cpp</depend>
  <depend>behaviortree_ros2</depend>
  <depend>ghost_v5_interfaces</depend>
  <depend>ghost_msgs</depend>
  
  // I really hope this works lmao (I judged that we needed this from the "#include "vex.h"" line in the example publisher code)
  <depend>vex</depend>
  
  // I'm not sure if we need these two, these are from the example publisher code
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
