# Drivetrain Motors
float32 drive_lf_angle
float32 drive_lb_angle
float32 drive_rf_angle
float32 drive_rb_angle
float32 drive_bl_angle
float32 drive_br_angle

float32 drive_lf_velocity
float32 drive_lb_velocity
float32 drive_rf_velocity
float32 drive_rb_velocity
float32 drive_bl_velocity
float32 drive_br_velocity


# Turret Encoder
float32 turret_angle
float32 turret_velocity

# Drivetrain Steering Encoders
float32 steering_left_angle
float32 steering_right_angle
float32 steering_back_angle

float32 steering_left_velocity
float32 steering_right_velocity
float32 steering_back_velocity

# Joystick Channels
float32 joystick_left_x
float32 joystick_left_y
float32 joystick_right_x
float32 joystick_right_y

# Joystick Buttons
bool joystick_btn_a
bool joystick_btn_b
bool joystick_btn_x
bool joystick_btn_y
bool joystick_btn_up
bool joystick_btn_down
bool joystick_btn_left
bool joystick_btn_right
bool joystick_btn_l1
bool joystick_btn_l2
bool joystick_btn_r1
bool joystick_btn_r2

# Competition state
bool is_disabled
bool is_autonomous
bool is_connected

# Digital Outputs
bool digital_out_1
bool digital_out_2
bool digital_out_3
bool digital_out_4
bool digital_out_5
bool digital_out_6
bool digital_out_7
bool digital_out_8
