# Header
std_msgs/Header header

# Joystick Channels
float32 joystick_left_x       # 0 -> 1.0
float32 joystick_left_y       # 0 -> 1.0
float32 joystick_right_x      # 0 -> 1.0
float32 joystick_right_y      # 0 -> 1.0

# Joystick Buttons
bool joystick_btn_a
bool joystick_btn_b
bool joystick_btn_x
bool joystick_btn_y
bool joystick_btn_up
bool joystick_btn_down
bool joystick_btn_left
bool joystick_btn_right
bool joystick_btn_l1
bool joystick_btn_l2
bool joystick_btn_r1
bool joystick_btn_r2