swerve_animator_node:
  ros__parameters:
    skip_factor: 10
    speedup_factor: 2.0

swerve_mpc_planner_node:
  ros__parameters:
    publish_intermediate_solutions: true
    ipopt_verbosity: 5
    max_iterations: 750

    time_horizon: 2.0
    dt: 0.05
    num_swerve_modules: 4

    chassis_width: 16.5
    wheel_base_width: 12.5
    wheel_diam: 2.75
    wheel_width: 1.0
    robot_mass: 10.0
    robot_inertia: 0.14868
    wheel_constraint_tolerance: 0.001

    default_state_weights:
      - 10000.0 # base_pose_x
      - 10000.0 # base_pose_y
      - 10000.0 # base_pose_theta
      - 0.0 # base_vel_x
      - 0.0 # base_vel_y
      - 0.0 # base_vel_theta
      - 0.0 # base_accel_x
      - 0.0 # base_accel_y
      - 0.0 # base_accel_theta

    default_joint_weights:
      - 0.0 # steering_angle
      - 1.0 # steering_vel
      - 0.00001 # steering_accel
      - 0.01 # wheel_vel
      - 0.01 # wheel_torque
      - 0.1 # lateral_force
