<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Steering Module Macro -->
    <xacro:macro name="steering_macro" params="id">
    <link name="mod_${id}">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.4545"/>
            <inertia
                ixx="0.000975" ixy="0.0" ixz="0.0"
                iyy="0.000975" iyz="0.0"
                izz="0.001902"/>
        </inertial>
    </link>
    </xacro:macro>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel_macro" params="id r_wheel width_wheel collision_factor">
    <link name="wheel_${id}">
            <visual>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel/collision_factor}"/>
                </geometry>
            </collision>

            <!--Inertia estimated for solid cylinder of radius 2.5" and height 1" with mass 1 lb-->
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.4545"/>
                <inertia
                    ixx="0.000482" ixy="0.0" ixz="0.0"
                    iyy="0.000482" iyz="0.0"
                    izz="0.000914"/>
            </inertial>
    </link>

    <gazebo reference="wheel_${id}">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder>
                    <radius>${r_wheel}</radius>
                    <length>${width_wheel/collision_factor}</length>
                </cylinder>
            </geometry>

            <surface>
                <friction>
                    <torsional>
                        <coefficient>1.0</coefficient>
                        <patch_radius>0.01</patch_radius>
                    </torsional>
                </friction>
            </surface>
        </collision>

        <material>Gazebo/White</material>
    </gazebo>
    </xacro:macro>
    
    <!-- Motor Macro -->
    <xacro:macro name="v5_motor_macro" params="joint_name link_name gear_ratio">
        <plugin name="${link_name}_motor_plugin" filename="libgazebo_motor_plugin.so">
        <joint_name>${joint_name}</joint_name>
        <link_name>${link_name}</link_name>

        <free_speed>130</free_speed>
        <stall_torque>4.5</stall_torque>
        <free_current>0.1</free_current>
        <stall_current>4.5</stall_current>
        <nominal_voltage>12.8</nominal_voltage>
        <gear_ratio>${gear_ratio}</gear_ratio>
        </plugin>
    </xacro:macro>
</robot>