competition_state_machine_node:
  ros__parameters:
    tank_robot_plugin:
      #normal auton init
      init_x_tiles: 1.0 # ignore
      init_y_tiles: 1.0 # ignore
      init_theta_degrees: 0.0
      # prog init
      # init_theta_degrees: 160.0
      # init_x_tiles: 0.5
      # init_y_tiles: 0.5
