std_msgs/Header header

uint32 msg_id

# Competition Status
ghost_msgs/V5CompetitionStatus competition_status

# Joystick States
ghost_msgs/V5JoystickState[] joysticks

# Rotation Sensor States
ghost_msgs/V5RotationSensorState[] rotation_sensors

# Inertial Sensor States
ghost_msgs/V5InertialSensorState[] inertial_sensors

# Motor States
ghost_msgs/V5MotorState[] motors

# Digital Devices
ghost_msgs/V5DigitalDeviceState[] digital_devices
