<?xml version="1.0"?>
<robot name="ghost1" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find ghost_description)/urdf/swerve_macros.xacro"/>

    <xacro:property name="dist_to_wheel" value="0.2286"/> <!-- 9" center to wheel modules-->
    <xacro:property name="r_wheel" value="0.034925"/> <!-- 1.375" wheel radius-->
    <xacro:property name="width_wheel" value="0.0254"/> <!-- 1" wheel width-->
    <xacro:property name="com_radius" value="0.02"/>
    <xacro:property name="d2r" value="${3.14159/180}"/>

    <link name="base_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.0127 0.29 0.0254"/>
        </geometry>
            <material name="silver">
                <color rgba="0.9 0.9 0.9 1.0"/>
            </material>
        </visual>

        <!--Inertia estimated for solid cylinder of radius 9" and height 3" with mass 7kg-->
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="10"/>
            <inertia
                ixx="0.094839" ixy="0.0" ixz="0.0"
                iyy="0.094839" iyz="0.0"
                izz="0.182903"/>
        </inertial>

        <gazebo>
            <maxVel>3.0</maxVel>
        </gazebo>
    </link>

    <link name="base_footprint">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.00001"/>
            <inertia
                ixx="0.00001" ixy="0.0" ixz="0.0"
                iyy="0.00001" iyz="0.0"
                izz="0.00001"/>
        </inertial>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.052585" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_bar">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.0127 0.35 0.0254"/>
        </geometry>
            <material name="silver">
                <color rgba="0.9 0.9 0.9 1.0"/>
            </material>
        </visual>
    </link>    

    <joint name="front_bar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_bar"/>
        <origin xyz="0.156 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_bar">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.0127 0.35 0.0254"/>
        </geometry>
            <material name="silver">
                <color rgba="0.9 0.9 0.9 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="left_bar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_bar"/>
        <origin xyz="-0.069 0.125 0" rpy="0 0 -1.0471"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_bar">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.0127 0.35 0.0254"/>
        </geometry>
            <material name="silver">
                <color rgba="0.9 0.9 0.9 1.0"/>
            </material>
    </visual>
    </link>

    <joint name="right_bar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_bar"/>
        <origin xyz="-0.069 -0.125 0" rpy="0 0 1.0471"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Steering Modules -->
    <xacro:steering_macro id="left"></xacro:steering_macro>
    <xacro:steering_macro id="right"></xacro:steering_macro>
    <xacro:steering_macro id="back"></xacro:steering_macro>
    <xacro:steering_macro id="top_test"></xacro:steering_macro>


    <!-- Wheel Modules -->
    <xacro:wheel_macro id="left" r_wheel="${r_wheel}" width_wheel="${width_wheel}" collision_factor="8"></xacro:wheel_macro>
    <xacro:wheel_macro id="right" r_wheel="${r_wheel}" width_wheel="${width_wheel}" collision_factor="8"></xacro:wheel_macro>
    <xacro:wheel_macro id="back" r_wheel="${r_wheel}" width_wheel="${width_wheel}" collision_factor="8"></xacro:wheel_macro>
    <xacro:wheel_macro id="top_test" r_wheel="${r_wheel}" width_wheel="${width_wheel}" collision_factor="8"></xacro:wheel_macro>

    <!-- Joints -->
    <joint name="steering_joint_left" type="continuous">
        <parent link="base_link"/>
        <child link="steering_link_left"/>
        <origin xyz="0.10452 0.180975 0.0812" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="steering_joint_right" type="continuous">
        <parent link="base_link"/>
        <child link="steering_link_right"/>
        <origin xyz="0.10452 -0.180975 0.0812" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="steering_joint_back" type="continuous">
        <parent link="base_link"/>
        <child link="steering_link_back"/>
        <origin xyz="-0.209 0.0 0.0812" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="steering_top_test" type="continuous">
        <parent link="base_link"/>
        <child link="steering_link_top_test"/>
        <origin xyz="0 0 0.0812" rpy="${180*d2r} 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="wheel_joint_left" type="continuous">
        <parent link="steering_link_left"/>
        <child link="wheel_link_left"/>
        <origin xyz="0 0 -0.09886" rpy="${90*d2r} 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="wheel_joint_right" type="continuous">
        <parent link="steering_link_right"/>
        <child link="wheel_link_right"/>
        <origin xyz="0 0 -0.09886" rpy="${90*d2r} 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="wheel_joint_back" type="continuous">
        <parent link="steering_link_back"/>
        <child link="wheel_link_back"/>
        <origin xyz="0 0 -0.09886" rpy="${90*d2r} 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="wheel_top_test" type="continuous">
        <parent link="steering_link_top_test"/>
        <child link="wheel_link_top_test"/>
        <origin xyz="0 0 -0.09886" rpy="${90*d2r} 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <axis xyz="0 0 0"/>
    </joint>
    <!-- Sensors -->
    <link name="lidar_link">
        <inertial>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            <mass value="0.125"/>
            <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <cylinder radius="${0.06985/2}" length="0.0254"/>
            </geometry>
        </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="-0.209 0 0.2145" rpy="0 0 ${67.562*d2r}"/>
    </joint>

    <!-- <link name="camera_base_link">
        <inertial>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            <mass value="0.125"/>
            <inertia ixx="0.001"  ixy="0.001"  ixz="0.001" iyy="0.001" iyz="0.001" izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_base_link"/>
        <origin xyz="${dist_to_wheel/2} 0 0.33" rpy="0 0 0"/>
    </joint>

    <link name="camera_view_link">
        <inertial>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            <mass value="0.125"/>
            <inertia ixx="0.001"  ixy="0.001"  ixz="0.001" iyy="0.001" iyz="0.001" izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_view_joint" type="fixed">
        <parent link="camera_base_link"/>
        <child link="camera_view_link"/>
        <origin xyz="0 0 0" rpy="0 0.7853975 0"/>
    </joint> -->
</robot>