motor_names:
  - "DRIVE_LEFT_FRONT_LEFT_MOTOR"
  - "DRIVE_LEFT_FRONT_RIGHT_MOTOR"
  - "DRIVE_LEFT_BACK_LEFT_MOTOR"
  - "DRIVE_LEFT_BACK_RIGHT_MOTOR"
  - "DRIVE_RIGHT_FRONT_LEFT_MOTOR"
  - "DRIVE_RIGHT_FRONT_RIGHT_MOTOR"
  - "DRIVE_RIGHT_BACK_LEFT_MOTOR"
  - "DRIVE_RIGHT_BACK_RIGHT_MOTOR"
  - "TURRET_MOTOR"