# animation_subscriber:
#   ros__parameters:
#     mode: playback
#     bool_test: true

marker_publisher:
  ros__parameters:
<<<<<<< HEAD
     mode: playback

# parameter:
#   mode: playback
=======
    mode: playback

# parameter:
#   mode: playback
>>>>>>> 31c97f91329df1e15cf447daf160c8c4a164f002
