port_configuration:
    devices:
        steering_front_right:
            port: 5
            type: ROTATION_SENSOR
            reversed: true
            config: steering_sensor_config
        drive_frr:
            port: 6
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_frl:
            port: 7
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_brf:
            port: 8
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_brb:
            port: 9
            type: MOTOR
            reversed: true
            config: drive_motor_config
        steering_back_right:
            port: 10
            type: ROTATION_SENSOR
            reversed: true
            config: steering_sensor_config
        steering_front_left:
            port: 15
            type: ROTATION_SENSOR
            reversed: true
            config: steering_sensor_config
        drive_flr:
            port: 16
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_fll:
            port: 17
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_blb:
            port: 18
            type: MOTOR
            reversed: true
            config: drive_motor_config
        drive_blf:
            port: 19
            type: MOTOR
            reversed: true
            config: drive_motor_config
        steering_back_left:
            port: 20
            type: ROTATION_SENSOR
            reversed: true
            config: steering_sensor_config

    device_configurations:
        steering_sensor_config:
            data_rate: 5
            serial:
                send_angle_data: true
                send_position_data: false
                send_velocity_data: true                
        drive_motor_config:
            gearset: 600
            brake_mode: COAST
            encoder_units: DEGREES
            controller:
                pos_gain: 0.0
                vel_gain: 10.0
                ff_vel_gain: 1.0
                ff_torque_gain: 0.0
            model:
                free_speed: 120.0
                stall_torque: 3.6
                free_current: 0.14
                stall_current: 4.25
                nominal_voltage: 12.0
                gear_ratio: 6.0
            serial:
                send_position_command: false
                send_velocity_command: true
                send_voltage_command: true
                send_torque_command: false
                send_torque_data: false
                send_voltage_data: false
                send_current_data: false
                send_power_data: false
                send_temperature_data: false
        stick_motor_config:
            gearset: 100
            brake_mode: COAST
            encoder_units: DEGREES
            controller:
                pos_gain: 0.0
                vel_gain: 10.0
                ff_vel_gain: 1.0
                ff_torque_gain: 0.0
            serial:
                send_position_command: false
                send_velocity_command: true
                send_voltage_command: true