port_configuration:
    devices:
        steering_front_left:
            port: 1
            type: ROTATION_SENSOR
            reversed: true
        drive_flr:
            port: 3
            type: MOTOR
            config: drive_motor_config
        drive_fll:
            port: 5
            type: MOTOR
            config: drive_motor_config
        drive_frr:
            port: 7
            type: MOTOR
            config: drive_motor_config
        drive_frl:
            port: 9
            type: MOTOR
            config: drive_motor_config
        steering_front_right:
            port: 10
            type: ROTATION_SENSOR
            reversed: true
        steering_back_left:
            port: 11
            type: ROTATION_SENSOR
            reversed: true
        drive_blr:
            port: 13
            type: MOTOR
            config: drive_motor_config
        drive_bll:
            port: 15
            type: MOTOR
            config: drive_motor_config
        drive_brl:
            port: 17
            type: MOTOR
            config: drive_motor_config
        drive_brr:
            port: 19
            type: MOTOR
            config: drive_motor_config
        steering_back_right:
            port: 20
            type: ROTATION_SENSOR
            reversed: true

    device_configurations:
        drive_motor_config:
            gearset: 600
            brake_mode: COAST
            encoder_units: DEGREES
            controller:
                pos_gain: 0.0
                vel_gain: 10.0
                ff_vel_gain: 1.0
                ff_torque_gain: 0.0
            model:
                free_speed: 120.0
                stall_torque: 3.6
                free_current: 0.14
                stall_current: 4.25
                nominal_voltage: 12.0
                gear_ratio: 6.0