ghost_serial_node:
  ros__parameters:
    port_name: "/dev/ttyACM1"
    backup_port_name: "/dev/ttyACM2"
    verbose: false

imu_filter_node:
  ros__parameters:
    calculate_bias: false
    calculate_covariance: false
    calibration_time: 5.0
    sensor_frequency: 200.0

    accel_bias_x: -0.136218
    accel_bias_y: -9.42483
    accel_bias_z: -2.90318

    gyro_bias_x: -0.0050632
    gyro_bias_y: 0.00207869
    gyro_bias_z: -0.000868592

    accel_covariance: [
      9.92618e-05, 1.36598e-06,  2.8624e-07,
      1.36598e-06, 0.000103017, 1.27159e-06,
      2.8624e-07, 1.27159e-06, 0.000110698]
    
    gyro_covariance: [
      4.09332e-06,  1.38296e-06, -2.18034e-07,
      1.38296e-06,  1.59246e-05, -4.90858e-07,
      -2.18034e-07, -4.90858e-07,  2.57037e-06]

    camera_roll: -110.0
    camera_pitch: 0.0
    camera_yaw: -90.0

    camera_x: 5.5
    camera_y: 4.75
    

competition_state_machine_node:
  ros__parameters:
    odom_topic: "/sensors/wheel_odom"
    pose_topic: "/estimation/robot_pose"

    swerve_robot_plugin:
      # If you are using the localization stack and you are tuning the k1-9 parameters,
      # the localization stack has its own duplicate (03_ROS/ghost_localization/config/ekf_pf_node.yaml) of the k1-9 parameters that must
      # be changed as well as this file. TODO: make a class for this
      # Motion Model Params
      # These calculate odometry standard deviations. X is forward, Y is left on robot.
      # Primary components are k1, k5, k9, which relate x travel to x error, y travel to y error, theta -> theta error.
      
      # Other values couple unrelated motions. These should be much smaller (and remember to account for units!)
      # EX. Y error from X Motion should be very small, but maybe the robot drifts slightly sideways as it tries to drive straight.

      # Remember that LIDAR will correct periodically, so these can be a bit generous.
      # Too generous though, and you are either losing resolution or wasting computation.

      k1: 0.1   # x error from x motion         # 50% error in primary direction
      k2: 0.02   #0.05   # x error from y motion         # Assume 10% drift via steering errors (hard to drive straight w swerve)       
      k3: 0.0   #0.1 # x error from rotation         # Pure rotation should be causing very little motion, 99% within 5" for 360째

      k4: 0.02   # 0.05   # y error from x motion         # Assume 10% drift via steering errors (hard to drive straight w swerve)  
      k5: 0.1   # y error from y motion         # 50% error in primary direction           
      k6: 0.0   # 0.1 # y error from rotation         # Pure rotation should be causing very little motion, 99% within 5" for 360째
      
      k7: 0.0   #0.2  # theta error from x motion     # After 2ft of travel, 99% are within by 5째   
      k8: 0.0   #0.2  # theta error from y motion     # After 2ft of travel, 99% are within by 5째 
      k9: 0.15   # theta error from rotation     # 50% error in primary direction  
