ghost_serial_node:
  ros__parameters:
    port_name: "/dev/ttyACM1"
    backup_port_name: "/dev/ttyACM2"
    verbose: false

imu_filter_node:
  ros__parameters:
    calculate_bias: false
    calculate_covariance: false
    calibration_time: 5.0
    sensor_frequency: 200.0

    accel_bias_x: -0.0623951
    accel_bias_y: -9.59332
    accel_bias_z: -2.17185

    gyro_bias_x: -0.00521851
    gyro_bias_y: 0.0019712
    gyro_bias_z: -0.000595768

    accel_covariance: [
      9.35244e-05, -9.52529e-07, -2.56578e-06,
      -9.52529e-07, 8.45894e-05, -9.63334e-07,
      -2.56578e-06, -9.63334e-07, 0.000119996]
    
    gyro_covariance: [
      4.06615e-06, 1.26211e-06, -1.72035e-08,
      1.26211e-06, 6.11825e-06, -1.98724e-08,
      -1.72035e-08, -1.98724e-08, 2.22475e-06]

    camera_roll: 90.0 #-105.0
    camera_pitch: 0.0
    camera_yaw: -90.0

    camera_x: 0.1651 # 6.5"
    camera_y: 0.0

competition_state_machine_node:
  ros__parameters:
    odom_topic: "/sensors/wheel_odom"
    pose_topic: "/estimation/robot_pose"

    swerve_robot_plugin:
      # If you are using the localization stack and you are tuning the k1-9 parameters,
      # the localization stack has its own duplicate (03_ROS/ghost_localization/config/ekf_pf_node.yaml) of the k1-9 parameters that must
      # be changed as well as this file. TODO: make a class for this
      # Motion Model Params
      # These calculate odometry standard deviations. X is forward, Y is left on robot.
      # Primary components are k1, k5, k9, which relate x travel to x error, y travel to y error, theta -> theta error.
      
      # Other values couple unrelated motions. These should be much smaller (and remember to account for units!)
      # EX. Y error from X Motion should be very small, but maybe the robot drifts slightly sideways as it tries to drive straight.

      # Remember that LIDAR will correct periodically, so these can be a bit generous.
      # Too generous though, and you are either losing resolution or wasting computation.

      k1: 0.5   # x error from x motion         # 50% error in primary direction
      k2: 0.05   # x error from y motion         # Assume 10% drift via steering errors (hard to drive straight w swerve)       
      k3: 0.1 # x error from rotation         # Pure rotation should be causing very little motion, 99% within 5" for 360째

      k4: 0.05   # y error from x motion         # Assume 10% drift via steering errors (hard to drive straight w swerve)  
      k5: 0.5   # y error from y motion         # 50% error in primary direction           
      k6: 0.1 # y error from rotation         # Pure rotation should be causing very little motion, 99% within 5" for 360째
      
      k7: 0.2  # theta error from x motion     # After 2ft of travel, 99% are within by 5째   
      k8: 0.2  # theta error from y motion     # After 2ft of travel, 99% are within by 5째 
      k9: 1.5   # theta error from rotation     # 50% error in primary direction  
