string name

uint8_t gpio_state_device_1     # GPIO state of IO Expander 1, 0 = low, 1 = high, 255 = undefined
uint8_t gpio_state_device_2     # GPIO state of IO Expander 2, 0 = low, 1 = high, 255 = undefined
uint8_t gpio_state_device_3     # GPIO state of IO Expander 3, 0 = low, 1 = high, 255 = undefined
uint8_t gpio_state_device_4     # GPIO state of IO Expander 4, 0 = low, 1 = high, 255 = undefined
uint8_t gpio_state_device_5     # GPIO state of IO Expander 5, 0 = low, 1 = high, 255 = undefined
