name: Learn Hello

on:
  workflow_dispatch:   # Only runs when you click "Run workflow" in the UI
  push:
    paths:
      - '.github/workflows/learn-hello.yml'   # Optional: only when this file changes

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      VEXU_HOME: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Show repo and branch
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          ls -la
          ls 09_External/plotjuggler
      - name: Script Test
        run: test -x "$VEXU_HOME/scripts/build.sh"