name: VEXU_GHOST

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ready_for_review, synchronize]

jobs:

  build-and-test:
    name: Build and Test
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04

    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - run: echo ${{github.workspace}}

      - name: Checkout
        uses: actions/checkout@v4
      
      - run: echo ${{github.workspace}}
      
      - run: ./scripts/build.sh

      - run: ./scripts/test_full.sh