<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Wheel Macro -->
    <xacro:macro name="wheel_macro" params="id r_wheel width_wheel collision_factor mu mu2 izz">
    <link name="wheel_link_${id}">
            <visual>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${r_wheel}" length="${width_wheel/collision_factor}"/>
                </geometry>              
            </collision>

            <!--Inertia estimated for solid cylinder of radius 2.5" and height 1" with mass 1 lb-->
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.4545"/>
                <inertia
                    ixx="0.000482" ixy="0.0" ixz="0.0"
                    iyy="0.000482" iyz="0.0"
                    izz="${izz}"/>
            </inertial>
    </link>

    <gazebo reference="wheel_link_${id}">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder>
                    <radius>${r_wheel}</radius>
                    <length>${width_wheel/collision_factor}</length>
                </cylinder>
            </geometry>

            <surface>
                <friction>
                <ode>
                    <mu>"${mu}"</mu>
                    <mu2>"${mu2}"</mu2> 
                    <fdir1>1 0 0</fdir1>
                </ode>                 
                </friction>
            </surface>
        </collision>

        <material>Gazebo/White</material>
    </gazebo>
    </xacro:macro>
</robot>